core:
  - changed-files:
      - any-glob-to-any-file: 'packages/core/**'

dashboard:
  - changed-files:
      - any-glob-to-any-file: 'packages/dashboard/**'

backend:
  - changed-files:
      - any-glob-to-any-file: 'packages/backend/**'

frontend:
  - changed-files:
      - any-glob-to-any-file: 'packages/frontend/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/package.json'
          - 'pnpm-lock.yaml'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
